### ISSUE TITLE
License

### ISSUE THREAD

**Issue by andrew-ebsco** [wevanscfi/Magento_CacheBuster#2]
Thanks for releasing this, it's a creative way to solve the cache issue.

Is this extension under a license? I would like to use it, but can't without an open source license.

**Comment by wevanscfi** [comment]
Sorry for they delay, this is a pretty old project of mine.

I have licensed this project under the [MIT open source license](https://github.com/wevanscfi/Magento_CacheBuster/pull/3). Please feel free to use it if you want
